Memeniac/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
	path('', include('main.urls')),
	path('user/', include('user.urls')),
    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

#views
from .views import (
	home,
	create_post,
	delete_post,
	rate_post,
	request_post_comment,
	create_comment,
	delete_comment,
	request_post
)

app_name = 'main'

urlpatterns = [
	path('', home, name='home'),
	path('post/create/', create_post, name='post-upload'),
	path('post/delete/', delete_post, name='post-delete'),
	path("post/rate/", rate_post, name='post-rate'),
	path('post/comment/request/', request_post_comment, name='post-comment-request'),
	path('post/comment/create/', create_comment, name='post-comment'),
	path('post/comment/<int:pk>/delete/', delete_comment, name='post-comment-delete'),
	path('post/request/', request_post, name='post-request'),
]

user/urls.py
from django.urls import path, reverse_lazy

from .views import (
	login_view,
	make_follow,
	create_account_view,
	edit_profile_view,
	profile,
	change_password_view,
	search_user,
	top_users,
)
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

app_name = 'user'

urlpatterns = [
	path('<int:pk>/profile', profile, name='profile'),
	path('<int:pk>/follow-unfollow', make_follow, name='follow'),
	path('create/', create_account_view, name='create'),
	path('login/', login_view, name='login'),
	path('change-passowrd/', change_password_view, name='change_pass'),

	path('logout/', LogoutView.as_view(next_page="main:home"), name='logout'),
	path('edit/', edit_profile_view, name='edit'),
	path('search/', search_user, name='search'),
	path('tops/', top_users, name='tops'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	date_posted = models.DateTimeField(default=timezone.now)

	def like_count(self):
		return self.rating_set.filter(name=Rating.LIKE).count()

	def dislike_count(self):
		return self.rating_set.filter(name=Rating.DISLIKE).count()

	def user_liked(self, user):
		try:
			rating = self.rating_set.get(user=user)
			return rating.name == Rating.LIKE
		except (Rating.DoesNotExist, Rating.MultipleObjectsReturned):
			return False

	def user_disliked(self, user):
		try:
			rating = self.rating_set.get(user=user)
			return rating.name == Rating.DISLIKE
		except (Rating.DoesNotExist, Rating.MultipleObjectsReturned):
			return False

	def make_rate(self, user, rate_name):
		if not rate_name in Rating.RATE_TYPES:
			raise ValueError('rate name not in default rate types')
		try:
			rating = user.rating_set.get(post_id=self.id)
			if rating.name == rate_name:
				rating.delete()
				return None
			rating.name = rate_name
			rating.save()
			return rating
		except Rating.DoesNotExist:
			return user.rating_set.create(post_id=self.id, name=rate_name)

	def get_unique_name(self):
		return f"{self.user.username}_post_{self.id}"

	def __str__(self):
		return f"{self.user.username} Post"

class Rating(models.Model):
	LIKE = 'like'
	DISLIKE = 'dislike'
	RATE_TYPES = [LIKE, DISLIKE]

	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
	name = models.CharField(max_length=32, null=True, blank=True)

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
	text_comment = models.TextField()
	date_commented = models.DateTimeField(default=timezone.now)

	def get_dic(self):
		return {
			'user':{
				'url': reverse('user:profile', kwargs={'id':self.user.id}),
				'id': self.user.id,
				'username': self.user.username,
				'picture_url': self.user.profile.picture.url,
			},
			'comment':{
				'id': self.pk,
				'date_commented': self.date_commented.strftime('%a. %b. %m %Y, %I %M %p'),
				'text_comment': self.text_comment,
			}
		}

class PostContent(models.Model):
	post = models.OneToOneField(Post, on_delete=models.CASCADE, primary_key=True)
	text_content = models.TextField(blank=True, null=True)

class Image(models.Model):
	post_content = models.ForeignKey(PostContent, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='PostContent/images/')

class PostListened(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	post_name = models.CharField(max_length=200)

main/forms.py
from django import forms
from .models import Post, PostContent , Image, Comment

from utils.custom_validators import is_valid_image
from django.core.validators import validate_image_file_extension


class PostForm(forms.Form):
	text_field = forms.CharField(widget=forms.Textarea, label="")
	image_field = forms.FileField(label="Add image", widget=forms.FileInput(attrs={
			'multiple': 'multiple',
			'accept': 'image/png,image/gif,image/jpeg'
		}))

	def __init__(self, *args, **kwargs):
		try:
			self.user = kwargs.pop('user')
		except KeyError:
			self.user = None
		super(PostForm, self).__init__(*args, **kwargs)

	def clean(self):
		cleaned_data = self.cleaned_data
		text_field = cleaned_data.get('text_field')
		self.images = self.files.getlist('image_field')
		self.errors.clear()

		if not self.user:
			raise forms.ValidationError('User is required')

		if text_field or len(self.images) > 0:
			for image in self.images:
				validate_image_file_extension(image)
				if not is_valid_image(image):
					self.add_error('image_field', 'image cant open or corrupted')
					break
		else:
			raise forms.ValidationError('Fill atleast one field')
		return cleaned_data

	def save(self):
		instance = Post(user=self.user)
		instance.save()
		postcontent = PostContent(post=instance)
		text_field = self.cleaned_data.get('text_field')
		if text_field:
			postcontent.text_content = text_field
		postcontent.save()
		for image in self.images:
			postcontent.image_set.create(image=image)
		return instance

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = [
			'text_comment'
		]

main/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic import DetailView

from django.http import HttpResponse, Http404
from django.template.loader import render_to_string

from user.forms import CreateAccountForm
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.forms import AuthenticationForm

from json import dumps as jdumps, loads as jloads

from .models import Post, Rating, PostContent, Image, Comment
from .forms import PostForm, CommentForm

def home(request):
	return render(request, 'main/home.html')


def create_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		response = {}
		postForm = PostForm(request.POST, request.FILES, user=request.user)
		if postForm.is_valid():
			instance = postForm.save()
			response['status'] = 1
			response['message'] = f"Post successfulyy created {instance.date_posted.strftime('%a. %b. %m %Y')}"
			response['post_html'] = render_to_string('main/post.html', context={'post': instance}, request=request)
			response['pid'] = instance.id
		else:
			response['status'] = 0
			response['errors'] = jloads(postForm.errors.as_json())
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def delete_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		pid = request.POST['pid']
		post = get_object_or_404(Post, pk=pid)
		post.delete()
		return HttpResponse(jdumps({'status': 1}), content_type="application/json")
	raise Http404()

def rate_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		pid = request.POST['pid']
		name = request.POST['name']
		if not name in Rating.RATE_TYPES:
			raise Http404()
		rating = get_object_or_404(Post, pk=pid).make_rate(request.user, name)
		return HttpResponse(jdumps({'active': rating.name if rating else None, 'selected': name}), content_type="application/json")
	else:
		raise Http404()

def request_post_comment(request):
	if request.method == 'GET' and request.is_ajax() and request.user.is_authenticated:
		pid = request.GET['pid']
		last_id = request.GET['last_id']
		include_form = request.GET['include_form']
		max_to_gen = 5
		response = {}

		if include_form:
			response['comment_form'] = render_to_string('main/comment-form.html', context={'pid': pid})

		if last_id == 'start':
			comment_list_all = get_object_or_404(Post, pk=pid).comment_set.all().order_by('-date_commented')
		else:
			comment_list_all = get_object_or_404(Post, pk=pid).comment_set.filter(id__lt=last_id).order_by('-date_commented')
		comment_list = comment_list_all[:max_to_gen]

		response['comments_html'] = "".join([render_to_string('main/comment.html', context={'comment': comment, 'user':request.user}) for comment in comment_list])
		response['last_id'] = comment_list[comment_list.count() - 1].id if comment_list.count() >= max_to_gen else 'end'
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def create_comment(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		response = {}
		pid = request.POST['pid']
		content = request.POST['content']
		if content:
			comment = request.user.comment_set.create(post_id=pid, text_comment=content)
			response['status'] = 1
			response['date_commented'] = comment.date_commented.strftime('%a. %b. %m %Y, %I %M %p')
		else:
			response['status'] = 0
			response['message'] = 'Empty content'
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def delete_comment(request, pk):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		get_object_or_404(Comment, pk=pk).delete()
		return HttpResponse(jdumps({}), content_type="application/json")
	raise Http404()

def request_post(request):
	if request.method == 'GET' and request.is_ajax():
		last_id = request.GET['last_id']
		filter_user = request.GET['filter_user']
		max_to_gen = 5

		if last_id == 'start':
			if filter_user:
				post_list_all = Post.objects.filter(user_id=filter_user)
			else:
				post_list_all = Post.objects.all().order_by('-date_posted')
		else:
			post_list_all = Post.objects.filter(id__lt=last_id).order_by('-date_posted')

		post_list = post_list_all[:max_to_gen]

		post_list_html = []
		post_list_pids = []

		for post in post_list:
			post_list_pids.append(post.id)
			post_list_html.append(
				render_to_string('main/post.html', context={'post': post}, request=request)
			)

		return HttpResponse(jdumps(
				{
					'post_list_html': post_list_html,
					'post_list_pids': post_list_pids,
					'max_lent': len(post_list_all),
					'last_id': post_list[post_list.count() - 1].id if post_list.count() >= max_to_gen else 'end'
				}
			), content_type="application/json")
	raise Http404()

main/templates/main/script/authentication.html
<script>
	$('#login-form-submit').on('click', (event) => {
		const loginForm = $('#login-form');
		const actionUrl = loginForm.attr('action');

		$('#login-form-error-message').remove();

		$.ajax({
			url: actionUrl,
			type: 'POST',
			data: new FormData(loginForm[0]),

			contentType: false,
			processData: false,

			success: (json) => {
				if(json.status === 1){
					window.location = json.redirect;
				}else{
					$('#login-form').prepend(
							`<div class="alert alert-danger" id="login-form-error-message">${json.message}</div>`
						);
				}
			},

			error: (xhr, errmsg, err) => {
				console.error(errmsg);
			}
		});

		event.preventDefault();
	});

	$('#crte-acc-form-submit').on('click', (event) => {
		var rgsterForm = $('#create-account-form');
		var actionUrl = "{% url 'user:create' %}";

		$('#rgster-valid-label').remove();
		$('#username-error').text('');
		$('#email-error').text('');
		$('#password1-error').text('');
		$('#password2-error').text('');

		$.ajax({
			url: actionUrl,
			type: 'POST',
			data: new FormData(rgsterForm[0]),

			contentType: false,
			processData: false,

			success: (json) => {
				if(json.status === 1){
					$('#create-account-form').prepend(
							`<div class="alert alert-success" id="rgster-valid-label">${json.message}</div>`
						);
					rgsterForm.trigger('reset');
				}
				else{
					if(json.username)
						$('#username-error').text('*'+json.username[0].message);
					if(json.email)
						$('#email-error').text('*'+json.email[0].message);
					if(json.password1)
						$('#password1-error').text('*'+json.password1[0].message);
					if(json.password2)
						$('#password2-error').text('*'+json.password2[0].message);
				}
			},

			error: (xhr, errmsg, err) => {
				console.error(errmsg);
			}
		});

		event.preventDefault();
	});
</script>

main/templates/main/script/post-script.html
{% load static %}

<script>
	function throwPostLoadedEvent(pid){
		var postloaded = $.Event('postloaded');
		postloaded.pid = pid;
		$(window).trigger(postloaded);
	};

	function Post(){
		this.onlike = (pid) => {};
		this.ondislike = (pid) => {};
		this.onCommentClick = (pid, last_id_input) => {};
		this.onCommentSend = (cid) => {};
		this.onCommentDelete = (href) => {};
		this.onSeeMore = (pid, last_id_input) => {};
		this.ondelete = (pid) => {};
		this.onedit = (pid) => {};

		this.getCommentArea = (pid) => {
			return $(`#post-container-${pid} .cmnt-area`);
		};

		this.setLikeCount = (pid, count) => {
			$(`#like-count-${pid} span`).text(count);
		};

		this.setDisLikeCount = (pid, count) => {
			$(`#dislike-count-${pid} span`).text(count);
		};

		this.setCommentCount = (pid, count) => {
			$(`#cmnt-count-${pid} span`).text(count);
		}

		this.setLikeState = (pid, isActive) => {
			$(`#post-container-${pid} .like svg`).removeClass('text-warning');
			if(isActive) $(`#post-container-${pid} .like svg`).addClass('text-warning');
		};

		this.setDisLikeState = (pid, isActive) => {
			$(`#post-container-${pid} .dislike svg`).removeClass('text-warning');
			if(isActive) $(`#post-container-${pid} .dislike svg`).addClass('text-warning');
		};

		this.disable = (pid) => {
			$(`#post-container-${pid} .cntnt-area`).addClass('disabled-post');
			$(`#post-container-${pid} .cmnt-area`).remove();
			$(`#post-container-${pid}`).append(`
					<div class="badge badge-warning badge-pill disabled-post-label d-flex align-items-center">
						<svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-exclamation-triangle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
						</svg>
						<span class="ml-1">this post has been deleted</span>
					</div>
				`)
		};

		function hasClass(elem, clas){
			return elem.classList.contains(clas);
		}

		$("#posts-container").on('click', '.post', (event) => {
			var post = event.currentTarget;
			var pid = post.getAttribute('pid');
			var target = event.target;
			var targetParent = target.parentNode;

			if(hasClass(targetParent, 'like'))
				this.onlike(pid);
			else if(hasClass(targetParent, 'dislike'))
				this.ondislike(pid);
			else if(hasClass(targetParent, 'comment'))
				this.onCommentClick(pid, $(`#post-container-${pid} .cmnt-area input[name='last_id']`));
			else if(hasClass(target, 'see-more'))
				this.onSeeMore(pid, $(`#post-container-${pid} .cmnt-area input[name='last_id']`));
			else if(hasClass(target, 'snd-cmnt')){
				this.onCommentSend(pid);
				$(`#cmnt-form-${pid} textarea`).val('');
				$(`#cmnt-form-${pid} .snd-cmnt`).addClass('disabled');
			}else if(hasClass(target, 'delete-post'))
				this.ondelete(pid);
			else if(hasClass(target, 'edit-post'))
				this.onedit(pid);
			else if(hasClass(target, 'delete-cmnt'))
				this.onCommentDelete(target.href);
			else
				return true;
			event.preventDefault();
		});

		$(window).on('postloaded', (event) => {
			
		});
	}

	function PostManager(){
		var lastPostPid = null;
		var maxPage = null;

		this.deletePost = (pid) => {
			$.ajax({
				'url': "{% url 'main:post-delete' %}",
				'type': 'POST',
				'data': {
					'pid': pid,
				},

				error: (xhr, errmsg, errThrow) => {
					console.error(errmsg);
				},
				headers: {'X_METHODOVERRIDE': 'DELETE'}
			});
		};

		this.sendRate = (pid, name, post) => {
			$.ajax({
				'async': false,
				'url': "{% url 'main:post-rate' %}",
				'type': 'POST',
				'data': {
					'pid': pid,
					'name': name
				},

				success: (json) => {
					post.setLikeState(pid, false);
					post.setDisLikeState(pid, false);
					if(json.active)
						json.active === 'like' ? post.setLikeState(pid, true) : post.setDisLikeState(pid, true);
				},
				error: (xhr, errmsg, errThrow) => {
					console.error(errmsg);
				}
			});
		};

		this.sendComment = (pid) => {
			var cmntForm = document.querySelector(`#cmnt-form-${pid}`);
			cmntForm.querySelector('.alert-cont').innerHTML = '';
			$.ajax({
				'url': "{% url 'main:post-comment' %}",
				'type': 'POST',
				'data': new FormData(cmntForm),

				contentType: false,
				processData: false,

				success: (json) => {
					if(json.status === 1){
						cmntForm.querySelector('.alert-cont').appendChild($(`<p class="sm-text">${json.date_commented}</p>`)[0]);
					}else{
						cmntForm.querySelector('.alert-cont').appendChild($(`<p class="sm-text">${json.message}</p>`)[0]);	
					}
				},

				error: (xhr, errmsg, errThrow) => {
					console.error(errmsg);
				}
			});
		};

		this.reqComment = (pid, last_id_input) => {
			var last_id = last_id_input.val();
			var include_form = last_id === 'start';
			$.ajax({
				'url': "{% url 'main:post-comment-request' %}",
				'type': 'GET',
				'data': {
					'pid': pid,
					'last_id': last_id,
					'include_form': include_form,
				},

				success: (json) => {
					$(`#post-container-${pid} .cmnt-cont .see-more`).remove();
					if(include_form)
						$(`#post-container-${pid} .cmnt-area`).prepend(json.comment_form);
					$(`#post-container-${pid} .cmnt-cont`).append(json.comments_html);
					if(json.last_id !== 'end')
						$(`#post-container-${pid} .cmnt-cont`).append($('<a href="#" class="see-more">see more...</a>')[0]);
					last_id_input.val(json.last_id);
				},

				error: (xhr, errmsg, errThrow) => {
					console.error(errmsg);
				}
			});
		};

		this.delComment = (href) => {
			$.ajax({
				'url': href,
				'type': 'POST',
				success: (json) => {
					console.log('deletion success');
				},
				error: (xhr, errmsg, errThrow) => {
					console.error(errmsg);
				}
			});
		};

		this.reqPost = (filter_user) => {
			if(lastPostPid != 'end'){
				$.ajax({
					'async': false,
					'url': "{% url 'main:post-request' %}",
					'type': 'GET',
					'data': {
						'last_id': lastPostPid ? lastPostPid : 'start',
						'filter_user': filter_user ? filter_user : ''
					},
					success: (json) => {
						lastPostPid = json.last_id;
						maxPage = json.max_lent;
						for(var post of json.post_list_html)
							$('#posts-container').append(post);
						for(var pid of json.post_list_pids)
							throwPostLoadedEvent(pid);
					},
					error: (xhr, errmsg, errThrow) => {
						console.error(errmsg);
					}
				});
			}
		};
	}

	$(window).on('load', (event) => {
		var postManager = new PostManager();

		var pathname = window.location.pathname;
		var userProfileUrlPatter = /(user)\/(\d+)\/(profile)/;
		var match = pathname.match(userProfileUrlPatter);
		var filter_user = match && match.length === 4 ? Number(match[2]) : null;

		$(window).on('scroll', (event) => {
			if ((window.innerHeight + window.scrollY) >= 0.9 * document.body.offsetHeight) {
				postManager.reqPost(filter_user);
		    }
		});

		{% if user.is_authenticated %}
			var post = new Post();

			post.onlike = (pid) => {
				postManager.sendRate(pid, 'like', post);
			};

			post.ondislike = (pid) => {
				postManager.sendRate(pid, 'dislike', post);
			};

			post.onCommentClick = (pid, last_id_input) => {
				if(last_id_input.val() === 'start'){
					postManager.reqComment(pid, last_id_input);
					last_id_input.val('');
				}
				else{
					var cmntCnt = post.getCommentArea(pid);
					cmntCnt.toggleClass('hide');
				}
			};

			post.onCommentSend = (pid) => {
				postManager.sendComment(pid);
			};

			post.onCommentDelete = (href) => {
				postManager.delComment(href);
			};

			post.onSeeMore = (pid, last_id_input) => {
				if(last_id_input.val() != 'end')
					postManager.reqComment(pid, last_id_input);
			};

			post.ondelete = (pid) => {
				var conf = new ConfModal('Delete this post ?');
				conf.onok = () => {
					postManager.deletePost(pid);
				};
			};

			function PostUpdatesEvent(){
				let webSocketUrl = 'ws://{{ request.get_host }}/ws/postupdates/';
				console.log('WebSocket URL:', webSocketUrl);
				var postUpdateSocket = new WebSocket(webSocketUrl);
				this.onPostDeletion = (pid) => {};
				this.onRateUpdate = (pid, name, like_count, dislike_count) => {};
				this.onNewComment = (pid, comment_html, new_comment_count) => {};
				this.onCommentDeletion = (pid, cid) => {};
				this.ready = (e) => {};
				this.listenTo = (pid) => {
					postUpdateSocket.send(JSON.stringify({
						'type': 'post_notif_request',
						'pid': pid
					}));
				}

				postUpdateSocket.onopen = (e) => {
					console.log('Post update socket opened', webSocketUrl);
					this.ready(e);
				};

				postUpdateSocket.onmessage = (event) => {
					var data = JSON.parse(event.data);
					switch(data.type){
						case 'post_deletion_broadcast':
							this.onPostDeletion(data.pid);
							break;
						case 'post_rate_update_broadcast':
							this.onRateUpdate(data.pid, data.name, data.like_count, data.dislike_count);
							break;
						case 'post_comment_update_broadcast':
							this.onNewComment(data.pid, data.comment_html, data.new_count);
							break;
						case 'post_comment_delete_broadcast':
							this.onCommentDeletion(data.pid, data.cid, data.new_count);
							break;
					}
				};
			}
			var postUpdates = new PostUpdatesEvent();

			postUpdates.ready = (e) => {
				$(window).on('postloaded', (event) => {
					postUpdates.listenTo(event.pid);
				});

				postUpdates.onPostDeletion = (pid) => {
					post.disable(pid);
				};

				postUpdates.onRateUpdate = (pid, name, like_count, dislike_count) => {
					post.setLikeCount(pid, like_count);
					post.setDisLikeCount(pid, dislike_count);
				};

				postUpdates.onNewComment = (pid, comment_html, new_comment_count) => {
					if($(`#post-container-${pid} .cmnt-area form`).length != 0)
						$(`#post-container-${pid} .cmnt-cont`).prepend(comment_html);
					post.setCommentCount(pid, new_comment_count);
				};

				postUpdates.onCommentDeletion = (pid, cid, new_comment_count) => {
					$(`#comment-${cid}`).remove();
					post.setCommentCount(pid, new_comment_count);
				};

				postManager.reqPost(filter_user);
			};
		{% else %}
			postManager.reqPost(filter_user);
			$(window).on('scroll', (event) => {
				if ((window.innerHeight + window.scrollY) >= 0.9 * document.body.offsetHeight) {
					postManager.reqPost(filter_user);
			    }
			});
		{% endif %}
	});
</script>

main/templates/main/script/user-script.html
<script>
	// var userUpdatesScoket = new WebSocket(`ws://${window.location.host}/ws/userupdates/`);

	// userUpdatesScoket.onmessage = (event) => {
	// 	// console.log(event.data);
	// };
</script>