Memeniac/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
	path('', include('main.urls')),
	path('user/', include('user.urls')),
    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

#views
from .views import (
	home,
	create_post,
	delete_post,
	rate_post,
	request_post_comment,
	create_comment,
	delete_comment,
	request_post
)

app_name = 'main'

urlpatterns = [
	path('', home, name='home'),
	path('post/create/', create_post, name='post-upload'),
	path('post/delete/', delete_post, name='post-delete'),
	path("post/rate/", rate_post, name='post-rate'),
	path('post/comment/request/', request_post_comment, name='post-comment-request'),
	path('post/comment/create/', create_comment, name='post-comment'),
	path('post/comment/<int:pk>/delete/', delete_comment, name='post-comment-delete'),
	path('post/request/', request_post, name='post-request'),
]

user/urls.py
from django.urls import path, reverse_lazy

from .views import (
	login_view,
	make_follow,
	create_account_view,
	edit_profile_view,
	profile,
	change_password_view,
	search_user,
	top_users,
)
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

app_name = 'user'

urlpatterns = [
	path('<int:pk>/profile', profile, name='profile'),
	path('<int:pk>/follow-unfollow', make_follow, name='follow'),
	path('create/', create_account_view, name='create'),
	path('login/', login_view, name='login'),
	path('change-passowrd/', change_password_view, name='change_pass'),

	path('logout/', LogoutView.as_view(next_page="main:home"), name='logout'),
	path('edit/', edit_profile_view, name='edit'),
	path('search/', search_user, name='search'),
	path('tops/', top_users, name='tops'),
]

user/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import IntegrityError


class Memer(AbstractUser):
	followers_count = models.IntegerField(default=0)

	def do_follow(self, other_memer):
		return self.followers.filter(follower=other_memer).exists()

	def follow_unfollow(self, follower):
		follow_info = FollowInfo.objects.filter(follower=follower, following=self)
		if follow_info.count() == 0:
			try:
				FollowInfo(follower=follower, following=self).save()
				return True
			except IntegrityError:
				pass
		follow_info.delete()
		return False

	def __str__(self):
		return self.username

class FollowInfo(models.Model):
	following = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followers')
	follower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followings')
	date_follow = models.DateTimeField(default=timezone.now)

	class Meta:
		unique_together = ['follower', 'following']
		ordering = ['-date_follow']

	def __str__(self):
		return f'{self.follower.username} follows {self.following.username}'


class Profile(models.Model):
	DEFAULT_PROFILE_PICTURE = 'Profile/pictures/default_profile_picture.jpg'
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
	picture = models.ImageField(default=DEFAULT_PROFILE_PICTURE, upload_to='Profile/pictures/')
	background = models.ImageField(default='Profile/background/default_background.jpg', upload_to='Profile/background/')
	about = models.TextField(blank=True, null=True)


class UserManager:
	def __init__(self, user):
		self.user = user

	def add_follower(self, user_to_add):
		if self.user == user_to_add:
			raise ValueError('user cannnot follow itself')
		followers = self.user.followers.filter(user=user_to_add)
		if followers.exists():
			followers.delete()
		else:
			self.user.followers.create(user=user_to_add)
		return self.user.followers.all()

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model
from .models import Profile

User = get_user_model()

class CreateAccountForm(UserCreationForm):
	email = forms.EmailField(label='Email')

	class Meta:
		model = User
		fields = [
			'username',
			'email',
			'password1',
			'password2'
		]

class ProfileForm(forms.Form):
	email = forms.EmailField(required=False)
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)
	profile_picture = forms.ImageField(required=False)
	background = forms.ImageField(required=False)

	def __init__(self, *args, **kwargs):
		try:
			self.uid = kwargs.pop('uid')
			super().__init__(*args, **kwargs)
		except KeyError:
			raise forms.ValidationError('profile form required uid value')
		except User.DoesNotExist:
			raise forms.ValidationError(f'user with uid {self.uid} does not exist')

	def save(self, *args, **kwargs):
		cleaned_data = self.cleaned_data
		user = User.objects.get(pk=self.uid)
		user.email = cleaned_data.get('email')
		user.first_name = cleaned_data.get('first_name')
		user.last_name = cleaned_data.get('last_name')

		profile_picture = cleaned_data.get('profile_picture')
		if profile_picture:
			user.profile.picture = profile_picture

		background = cleaned_data.get('background')
		if background:
			user.background = background
			
		user.save()
		user.profile.save()
		return user

user/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse

from django.http import HttpResponse, Http404

from django.contrib.auth import authenticate, login

from django.contrib.auth.forms import AuthenticationForm
from .forms import CreateAccountForm, ProfileForm

from json import dumps as jdumps, loads as jloads

from .models import Profile, UserManager
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm

from django.db.models import Q

User = get_user_model()

def profile(request, pk):
	user = get_object_or_404(User, pk=pk)
	return render(request, 'main/profile-detail.html', {
			'target_user': user,
		})

def make_follow(request, pk):
	if request.method == 'POST' and request.user.is_authenticated and request.is_ajax():
		memer = get_object_or_404(User, pk=pk)
		do_follow = memer.follow_unfollow(request.user)
		return HttpResponse(jdumps({'do_follow':do_follow, 'new_followers_count': get_object_or_404(User, pk=pk).followers_count}), content_type='application/json')
	raise Http404()
	
def login_view(request):
	if request.method == 'POST' and request.is_ajax():
		response = {}
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user:
			response['status'] = 1
			response['redirect'] = reverse("main:home")
			login(request, user)
			return HttpResponse(jdumps(response), content_type='application/json')
		else:
			response['status'] = 0
			response['message'] = "Invalid username or password."
			return HttpResponse(jdumps(response), content_type='application/json')
	else:
		raise Http404()

def create_account_view(request):
	if request.method == 'POST' and request.is_ajax():
		create_account_form = CreateAccountForm(request.POST)
		if create_account_form.is_valid():
			create_account_form.save()
			return HttpResponse(jdumps({
					'status': 1,
					'message':'Account created successfuly',
				}), content_type='application/json')
		else:
			data = jloads(create_account_form.errors.as_json())
			data['status'] = 0
			return HttpResponse(jdumps(data), content_type='application/json')
	else:
		raise Http404()

def change_password_view(request):
	if not request.user.is_authenticated:
		return Http404()
	context = {}
	context['change_pass_form'] = PasswordChangeForm(user=request.user)
	if request.method == 'POST':
		change_pass_form = PasswordChangeForm(user=request.user, data=request.POST)
		context['change_pass_form'] = change_pass_form
		if change_pass_form.is_valid():
			user = change_pass_form.save()
			login(request, user)
			del context['change_pass_form']
			context['message'] = 'Changing password successfully'
	return render(request, 'user/change-pass.html', context)

def edit_profile_view(request):
	if request.method == 'POST' and request.user.is_authenticated and 'uid' in request.POST:
		profileForm = ProfileForm(request.POST, request.FILES, uid=request.POST['uid'])
		response = jloads(profileForm.errors.as_json())
		if profileForm.is_valid():
			profileForm.save()
			response['status'] = 1
			return HttpResponse(jdumps(response), content_type='application/json')
		response['status'] = 0
		return HttpResponse(jdumps(response), content_type='application/json')
	raise HttpResponse()

def search_user(request):
	if request.method == 'GET' and request.is_ajax():
		max_results = 5
		username = request.GET['username']
		users = User.objects.filter(username__istartswith=username)
		results = []
		for user in users[:max_results]:
			results.append({
				'username': user.username,
				'profile_picture_url': user.profile.picture.url,
				'link': reverse('user:profile', kwargs={'pk':user.id})
			})
		return HttpResponse(jdumps({'results': results, 'results_count': users.count()}), content_type='application/json')

def top_users(request):
	if request.method == 'GET' and request.is_ajax() and request.user.is_authenticated:
		max_results = 5
		top_users_obj = User.objects.filter(followers_count__gt=0).order_by('-followers_count')[:max_results]
		top_users = []
		for user in top_users_obj:
			top_users.append({
				'link': reverse('user:profile', kwargs={'pk':user.id}),
				'profile_picture_url': user.profile.picture.url,
				'username': user.username,
				'followers_count': user.followers_count,
			})
		return HttpResponse(jdumps({'top_users':top_users}), content_type='application/json')

user/templates/user/change-pass.html
{% extends 'main/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 border border-warning bg-light">
				
				<div class="my-2">
					{% if message %}
						<div class="alert alert-success my-1">
							{{ message }}
						</div>
						<a href="{% url 'main:home' %}">go to home...</a>
					{% endif %}
				</div>
				
				{% if change_pass_form %}
					<div class="m-2">
						<form method="POST">
							{% csrf_token %}
							{{ change_pass_form|crispy }}
							<button type="submit" class="w-100 btn btn-outline-warning">change</button>
						</form>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock content %}

user/templates/user/login-register-modal.html
{% load form-filter %}

<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content bg-light">
			<div class="modal-header bg-light">
				<h5 class="modal-title text-warning">memeniac</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body pt-0">
				<div class="d-flex justify-content-around p-0 my-1">
					<button class="w-100 btn btn-outline-warning rounded-0" role="button" onmouseup="$('.carousel').carousel(0);">
						LOGIN
						<span class="sr-only">Previous</span>
					</button>
					<button class="w-100 btn btn-outline-warning rounded-0" role="button" onmouseup="$('.carousel').carousel(1);">
						REGISTER
						<span class="sr-only">Next</span>
					</button>
				</div>
				<div class="carousel slide" data-ride="carousel" id="carousel-form-slide" data-interval="false">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<form method="POST" id="login-form" action="{% url 'user:login' %}">
								{% csrf_token %}
								<label for="{{ login_form.username.id }}">{{ login_form.username.label }}</label>
								{% attrs login_form.username class='form-control mb-2' autofocus='' %}
								{% csrf_token %}
								<label for="{{ login_form.password.id }}">{{ login_form.password.label }}</label>
								{% attrs login_form.password class='form-control mb-2' %}
								<button type="submit" class="btn btn-warning col-3 mr-2" id="login-form-submit">Login</button>
								<p href="" class="float-right">Forgot password ?<a href="{% url 'password_reset' %}" class="ml-2">Click here.</a></p>
							</form>
						</div>
						<div class="carousel-item">
							<form method="POST" id="create-account-form">
								{% csrf_token %}
								<div class="form-group">
									{% attrs create_account_form.username class='form-control' id='id_username_register' placeholder=create_account_form.username.label %}
									<div class="text-danger p-0 m-0" id="username-error"></div>
								</div>
								<div class="form-group">
									{% attrs create_account_form.email class='form-control' placeholder=create_account_form.email.label %}
									<div class="text-danger p-0 m-0" id="email-error"></div>
								</div>
								<div class="form-group">
									{% attrs create_account_form.password1 class='form-control' placeholder=create_account_form.password1.label %}
									<div class="text-danger p-0 m-0" id="password1-error"></div>
								</div>
								<div class="form-group">
									{% attrs create_account_form.password2 class='form-control' placeholder=create_account_form.password2.label %}
									<div class="text-danger p-0 m-0" id="password2-error"></div>
								</div>
								<button type="submit" class="float-right btn btn-warning col-3" id="crte-acc-form-submit">Register</button>
								<button type="reset" style="display: none;" id="create_account_form_reset"></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

user/templates/user/password_reset.html
{% extends 'main/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 border border-warning bg-light py-2">
				<p>Enter your recovery email.</p>
				<form method="POST">
					{% csrf_token %}
					{{ form|crispy }}
					<button type="submit" class="w-100 btn btn-outline-warning">submit</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

user/templates/user/password_reset_complete.html
{% extends 'main/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 border border-warning bg-light">
				<div class="alert alert-success">
					Password reset complete return <a href="{% url 'main:home' %}">home.</a>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

user/templates/user/password_reset_confirm.html
{% extends 'main/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 border border-warning bg-light py-2">
				{% if validlink %}
					<form method="POST">
						{% csrf_token %}
						{{ form|crispy }}
						<button class="btn btn-warning w-100">reset</button>
					</form>
				{% else %}
					<div class="alert alert-warning">
						This password reset link was invalid. Please request a new one.
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock content %}

user/templates/user/password_reset_done.html
{% extends 'main/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 border border-warning bg-light py-2">
				<div class="alert alert-success">
					Weve emailed you a link to reset your password. Please check your inbox.
				</div>
			</div>
		</div>
	</div>
{% endblock content %}