Memeniac/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
	path('', include('main.urls')),
	path('user/', include('user.urls')),
    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html'), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

#views
from .views import (
	home,
	create_post,
	delete_post,
	rate_post,
	request_post_comment,
	create_comment,
	delete_comment,
	request_post
)

app_name = 'main'

urlpatterns = [
	path('', home, name='home'),
	path('post/create/', create_post, name='post-upload'),
	path('post/delete/', delete_post, name='post-delete'),
	path("post/rate/", rate_post, name='post-rate'),
	path('post/comment/request/', request_post_comment, name='post-comment-request'),
	path('post/comment/create/', create_comment, name='post-comment'),
	path('post/comment/<int:pk>/delete/', delete_comment, name='post-comment-delete'),
	path('post/request/', request_post, name='post-request'),
]

user/urls.py
from django.urls import path, reverse_lazy

from .views import (
	login_view,
	make_follow,
	create_account_view,
	edit_profile_view,
	profile,
	change_password_view,
	search_user,
	top_users,
)
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

app_name = 'user'

urlpatterns = [
	path('<int:pk>/profile', profile, name='profile'),
	path('<int:pk>/follow-unfollow', make_follow, name='follow'),
	path('create/', create_account_view, name='create'),
	path('login/', login_view, name='login'),
	path('change-passowrd/', change_password_view, name='change_pass'),

	path('logout/', LogoutView.as_view(next_page="main:home"), name='logout'),
	path('edit/', edit_profile_view, name='edit'),
	path('search/', search_user, name='search'),
	path('tops/', top_users, name='tops'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	date_posted = models.DateTimeField(default=timezone.now)

	def like_count(self):
		return self.rating_set.filter(name=Rating.LIKE).count()

	def dislike_count(self):
		return self.rating_set.filter(name=Rating.DISLIKE).count()

	def user_liked(self, user):
		try:
			rating = self.rating_set.get(user=user)
			return rating.name == Rating.LIKE
		except (Rating.DoesNotExist, Rating.MultipleObjectsReturned):
			return False

	def user_disliked(self, user):
		try:
			rating = self.rating_set.get(user=user)
			return rating.name == Rating.DISLIKE
		except (Rating.DoesNotExist, Rating.MultipleObjectsReturned):
			return False

	def make_rate(self, user, rate_name):
		if not rate_name in Rating.RATE_TYPES:
			raise ValueError('rate name not in default rate types')
		try:
			rating = user.rating_set.get(post_id=self.id)
			if rating.name == rate_name:
				rating.delete()
				return None
			rating.name = rate_name
			rating.save()
			return rating
		except Rating.DoesNotExist:
			return user.rating_set.create(post_id=self.id, name=rate_name)

	def get_unique_name(self):
		return f"{self.user.username}_post_{self.id}"

	def __str__(self):
		return f"{self.user.username} Post"

class Rating(models.Model):
	LIKE = 'like'
	DISLIKE = 'dislike'
	RATE_TYPES = [LIKE, DISLIKE]

	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
	name = models.CharField(max_length=32, null=True, blank=True)

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
	text_comment = models.TextField()
	date_commented = models.DateTimeField(default=timezone.now)

	def get_dic(self):
		return {
			'user':{
				'url': reverse('user:profile', kwargs={'id':self.user.id}),
				'id': self.user.id,
				'username': self.user.username,
				'picture_url': self.user.profile.picture.url,
			},
			'comment':{
				'id': self.pk,
				'date_commented': self.date_commented.strftime('%a. %b. %m %Y, %I %M %p'),
				'text_comment': self.text_comment,
			}
		}

class PostContent(models.Model):
	post = models.OneToOneField(Post, on_delete=models.CASCADE, primary_key=True)
	text_content = models.TextField(blank=True, null=True)

class Image(models.Model):
	post_content = models.ForeignKey(PostContent, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='PostContent/images/')

class PostListened(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	post_name = models.CharField(max_length=200)

main/forms.py
from django import forms
from .models import Post, PostContent , Image, Comment

from utils.custom_validators import is_valid_image
from django.core.validators import validate_image_file_extension


class PostForm(forms.Form):
	text_field = forms.CharField(widget=forms.Textarea, label="")
	image_field = forms.FileField(label="Add image", widget=forms.FileInput(attrs={
			'multiple': 'multiple',
			'accept': 'image/png,image/gif,image/jpeg'
		}))

	def __init__(self, *args, **kwargs):
		try:
			self.user = kwargs.pop('user')
		except KeyError:
			self.user = None
		super(PostForm, self).__init__(*args, **kwargs)

	def clean(self):
		cleaned_data = self.cleaned_data
		text_field = cleaned_data.get('text_field')
		self.images = self.files.getlist('image_field')
		self.errors.clear()

		if not self.user:
			raise forms.ValidationError('User is required')

		if text_field or len(self.images) > 0:
			for image in self.images:
				validate_image_file_extension(image)
				if not is_valid_image(image):
					self.add_error('image_field', 'image cant open or corrupted')
					break
		else:
			raise forms.ValidationError('Fill atleast one field')
		return cleaned_data

	def save(self):
		instance = Post(user=self.user)
		instance.save()
		postcontent = PostContent(post=instance)
		text_field = self.cleaned_data.get('text_field')
		if text_field:
			postcontent.text_content = text_field
		postcontent.save()
		for image in self.images:
			postcontent.image_set.create(image=image)
		return instance

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = [
			'text_comment'
		]

main/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic import DetailView

from django.http import HttpResponse, Http404
from django.template.loader import render_to_string

from user.forms import CreateAccountForm
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.forms import AuthenticationForm

from json import dumps as jdumps, loads as jloads

from .models import Post, Rating, PostContent, Image, Comment
from .forms import PostForm, CommentForm

def home(request):
	return render(request, 'main/home.html')


def create_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		response = {}
		postForm = PostForm(request.POST, request.FILES, user=request.user)
		if postForm.is_valid():
			instance = postForm.save()
			response['status'] = 1
			response['message'] = f"Post successfulyy created {instance.date_posted.strftime('%a. %b. %m %Y')}"
			response['post_html'] = render_to_string('main/post.html', context={'post': instance}, request=request)
			response['pid'] = instance.id
		else:
			response['status'] = 0
			response['errors'] = jloads(postForm.errors.as_json())
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def delete_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		pid = request.POST['pid']
		post = get_object_or_404(Post, pk=pid)
		post.delete()
		return HttpResponse(jdumps({'status': 1}), content_type="application/json")
	raise Http404()

def rate_post(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		pid = request.POST['pid']
		name = request.POST['name']
		if not name in Rating.RATE_TYPES:
			raise Http404()
		rating = get_object_or_404(Post, pk=pid).make_rate(request.user, name)
		return HttpResponse(jdumps({'active': rating.name if rating else None, 'selected': name}), content_type="application/json")
	else:
		raise Http404()

def request_post_comment(request):
	if request.method == 'GET' and request.is_ajax() and request.user.is_authenticated:
		pid = request.GET['pid']
		last_id = request.GET['last_id']
		include_form = request.GET['include_form']
		max_to_gen = 5
		response = {}

		if include_form:
			response['comment_form'] = render_to_string('main/comment-form.html', context={'pid': pid})

		if last_id == 'start':
			comment_list_all = get_object_or_404(Post, pk=pid).comment_set.all().order_by('-date_commented')
		else:
			comment_list_all = get_object_or_404(Post, pk=pid).comment_set.filter(id__lt=last_id).order_by('-date_commented')
		comment_list = comment_list_all[:max_to_gen]

		response['comments_html'] = "".join([render_to_string('main/comment.html', context={'comment': comment, 'user':request.user}) for comment in comment_list])
		response['last_id'] = comment_list[comment_list.count() - 1].id if comment_list.count() >= max_to_gen else 'end'
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def create_comment(request):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		response = {}
		pid = request.POST['pid']
		content = request.POST['content']
		if content:
			comment = request.user.comment_set.create(post_id=pid, text_comment=content)
			response['status'] = 1
			response['date_commented'] = comment.date_commented.strftime('%a. %b. %m %Y, %I %M %p')
		else:
			response['status'] = 0
			response['message'] = 'Empty content'
		return HttpResponse(jdumps(response), content_type="application/json")
	raise Http404()

def delete_comment(request, pk):
	if request.method == 'POST' and request.is_ajax() and request.user.is_authenticated:
		get_object_or_404(Comment, pk=pk).delete()
		return HttpResponse(jdumps({}), content_type="application/json")
	raise Http404()

def request_post(request):
	if request.method == 'GET' and request.is_ajax():
		last_id = request.GET['last_id']
		filter_user = request.GET['filter_user']
		max_to_gen = 5

		if last_id == 'start':
			if filter_user:
				post_list_all = Post.objects.filter(user_id=filter_user)
			else:
				post_list_all = Post.objects.all().order_by('-date_posted')
		else:
			post_list_all = Post.objects.filter(id__lt=last_id).order_by('-date_posted')

		post_list = post_list_all[:max_to_gen]

		post_list_html = []
		post_list_pids = []

		for post in post_list:
			post_list_pids.append(post.id)
			post_list_html.append(
				render_to_string('main/post.html', context={'post': post}, request=request)
			)

		return HttpResponse(jdumps(
				{
					'post_list_html': post_list_html,
					'post_list_pids': post_list_pids,
					'max_lent': len(post_list_all),
					'last_id': post_list[post_list.count() - 1].id if post_list.count() >= max_to_gen else 'end'
				}
			), content_type="application/json")
	raise Http404()

main/templates/main/comment-form.html

<form id="cmnt-form-{{ pid }}" class="px-2">
	{% csrf_token %}
	<input type="text" name="pid" value="{{ pid }}" hidden="">
	<div class="d-flex py-1">
		<textarea class="form-control md-text" rows="2" style="max-height: 12em;" placeholder="Write comment here..." name="content" required></textarea>
		<a class="btn disabled btn-warning ml-1 snd-cmnt" role="button">send</a>
	</div>
	<div class="alert-cont ml-1"></div>
</form>

<script>
	$('#cmnt-form-{{ pid }} textarea').on('keyup change', (event) => {
		var txtL = event.currentTarget.value.length;
		if(txtL > 0) $('#cmnt-form-{{ pid }} .snd-cmnt').removeClass('disabled');
		else $('#cmnt-form-{{ pid }} .snd-cmnt').addClass('disabled');
	});
</script>

main/templates/main/comment.html
<div class="media mx-3 my-2 bg-light rounded p-2 shadow-sm border border-warning" id="comment-{{ comment.id }}">
	<a href="{% url 'user:profile' comment.user.id %}" class="rounded-circle mr-2">
		<img class="rounded-circle" src="{{ comment.user.profile.picture.url }}" width="32" height="32" class="mr-2">
	</a>
	<div class="media-body">
		<h5 class="m-0 sm-text">{{ comment.user.username }}</h5>
		<p class="m-0 sm-text">{{ comment.date_commented|date:"D. M. d Y, g:i a" }}</p>
		<div class="border-bottom p-1">
			<p class="md-text m-0">{{ comment.text_comment }}</p>
		</div>
		{% if user == comment.user %}
			<div class="float-right">
				<a href="{% url 'main:post-comment-delete' comment.id %}" class="md-text ml-auto delete-cmnt">delete</a>
			</div>
		{% endif %}
	</div>
</div>

main/templates/main/home.html
{% extends 'main/index.html' %}

{% load static %}

{% block content %}
	<main class="container mt-2">
		<div class="row justify-content-center">
			<div class="col-lg-3">
				<div class="d-flex flex-column">
					
					{% if user.is_authenticated %}
						<div class="rounded-top my-2 d-flex p-2 align-items-center bg-light border border-warning">
							<a href="{% url 'user:profile' user.id %}">
								<img class="rounded-circle border border-warning mr-3" src="{{ user.profile.picture.url }}" width="64" height="64">
							</a>
							<div>
								<p class="text-primary md-text m-0">{{ user.username }}</p>
								<p class="md-text m-0">Post: {{ user.post_set.all.count }}</p>
							</div>
						</div>
					{% else %}
						<div class="rounded-top justify-content-center my-3 bg-light">
							<button type="button" class="btn btn-outline-success btn-sm col" data-toggle="modal" data-target="#form-modal"><span class="text-warning">LOGIN/REGISTER</span></button>
						</div>
					{% endif %}

					{% include 'main/top-users.html' %}
				</div>

			</div>
			<div class="col-lg-6 mx-1">
				<div class="my-2">
					{% include 'main/post-form.html' with post_form=post_form %}
				</div>
				<div id="posts-container"></div>
			</div>
		</div>
	</main>
{% endblock content %}

main/templates/main/index.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0/bootstrap.min.css' %}">

		<!-- CUSTOM CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">

		<title>Memeniac</title>
	</head>
	<body>
		<header>
			<nav class="navbar border-bottom border-warning fixed-top navbar-expand navbar-light bg-light">
				<div class="container">
					<a class="navbar-brand text-warning" href="{% url 'main:home' %}">
						<img class="logo bg-warning rounded-circle" src="{% static 'web-images/troll-face-logo.svg' %}" width="32" height="32">
						<span id="logo-label">memeniac</span>
					</a>
					<button class="navbar-toggler bg-warning" type="button" data-toggle="collapse" data-target="#navbar-navs" aria-controls="navbar-navs" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbar-navs">
						<form class="form-inline my-2">
							<div class="dropdown">
								<div class="input-group input-group-sm md-form form-sm form-2 pl-0">
									<input id="user-search-box" class="form-control my-0 py-1 warning-border" type="text" placeholder="Search" aria-label="Search" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<div class="input-group-append">
										<span class="input-group-text red lighten-3" id="basic-text1">
											<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
												<path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
												<path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
											</svg>
										</span>
									</div>
									<div id="search-results" class="dropdown-menu w-100" aria-labelledby="user-search-box"></div>
								</div>
							</div>
						</form>
					</div>
					<div class="collapse navbar-collapse">
						{% if user.is_authenticated %}
							<div class="ml-auto navbar-nav">
								<div class="dropdown">
									<button data-toggle="dropdown" type="button" id="profile-option" aria-haspopup="true" aria-expanded="false">
										<img class="rounded-circle border border-warning" src="{{ user.profile.picture.url }}" width="42" height="42">
										<span id="nav_user_username" class="text-warning">{{ user.username }}</span>
									</button>
									<div class="dropdown-menu dropdown-menu-right" aria-labelledby="profile-option">
										<a href="{% url 'user:profile' user.id %}" class="dropdown-item" type="button">profile</a>
										<a href="{% url 'user:logout' %}" class="dropdown-item" type="button">logout</a>
										<a href="{% url 'user:change_pass' %}" class="dropdown-item" type="button">change password</a>
									</div>
								</div>
							</div>
						{% endif %}
					</div>
				</div>
			</nav>
		</header>

		{% block content %}
		{% endblock content %}

		<div id="post-modal" class="post-modal">
			<span class="close">&times;</span>
		</div>

		{% if not user.is_authenticated %}
			{% include 'user/login-register-modal.html' %}
		{% endif %}

		<script src="{% static 'main/js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
		<script type="text/javascript" src="{% static 'bootstrap-4.0.0/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'bootstrap-4.0.0/bootstrap.min.js' %}"></script>
		<script>
			var sendSearchedID = null;

			$('#user-search-box').on('change keyup focus', (event) => {
				var searchedName = $('#user-search-box').val().trim();
				if(!$('#search-results').hasClass('show'))
					$('#user-search-box').dropdown('toggle');
				clearTimeout(sendSearchedID);
				if(searchedName.length > 0){
					sendSearchedID = setTimeout(() => {
						$.ajax({
							'url': "{% url 'user:search' %}",
							'type': 'GET',
							'data': {
								'username': searchedName
							},
							success: (json) => {
								var results = "";
								for(let user of json.results){
									results += `
										<a href="${user.link}" class="dropdown-item search-result-item" type="button"><img class="rounded-circle mr-2" src="${user.profile_picture_url}" width="32" height="32">${user.username}</a>
									`;
								}
								results += `
									<p class="dropdown-header sm-text border-top border-warning p-0 mt-2 pl-2">results: ${json.results_count}</p>
								`
								$('#search-results').html(results);
							},
							error: (xhr, errmsg, errThrow) => {
								console.error(errmsg);
							}
						});
					}, 700);
				}else{
					$('#search-results').html('');
				}
			});
		</script>

		{% if user.is_authenticated %}
			<script>
				function getCookie(name) {
				    var cookieValue = null;
				    if (document.cookie && document.cookie !== '') {
				        var cookies = document.cookie.split(';');
				        for (var i = 0; i < cookies.length; i++) {
				            var cookie = cookies[i].trim();
				            // Does this cookie string begin with the name we want?
				            if (cookie.substring(0, name.length + 1) === (name + '=')) {
				                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
				                break;
				            }
				        }
				    }
				    return cookieValue;
				}

				var csrftoken = getCookie('csrftoken');

				function csrfSafeMethod(method) {
				    // these HTTP methods do not require CSRF protection
				    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
				}
				$.ajaxSetup({
				    beforeSend: function(xhr, settings) {
				        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
				            xhr.setRequestHeader("X-CSRFToken", csrftoken);
				        }
				    }
				});

				function CurrentUser(){
					return {
						'id': Number('{{ user.id }}'),
						'username': '{{ user.username }}',
					};
				}
			</script>
			{% include 'main/script/user-script.html' %}
		{% else %}
			{% include 'main/script/authentication.html' %}
		{% endif %}

		{% include 'main/script/post-script.html' %}

		<script src="{% static 'main/js/script.js' %}" type="text/javascript"></script>
	</body>
</html>

main/templates/main/post-form.html
{% load form-filter %}

{% if user.is_authenticated %}
	<div class="p-2 rounded-top border border-warning">
		<p>Create post</p>
		<form id="post-form" action="{% url 'main:post-upload' %}">
			{% csrf_token %}
			{% attrs post_form.text_field class='form-control' style='height:128px; max-height:264px;' placeholder='Add some thoughts..' %}
			{% attrs post_form.image_field hidden='' %}
		</form>
		<div id="selected-images-field" class="w-100">
		</div>
		<div class="badge badge-light badge-pill w-100 px-2 my-1 p-1 d-flex border border-warning">
			<button id="add-image">
				<span class="badge badge-warning badge-pill md-text d-flex align-items-center">
					<svg width="1.4em" height="1.4em" viewBox="0 0 16 16" class="bi bi-image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd" d="M14.002 2h-12a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zm-12-1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12z"/>
						<path d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V14h-14v-2l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z"/>
						<path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
					</svg>
					image
				</span>
			</button>
			<button class="ml-auto" id="add-post">
				<span class="badge badge-success badge-pill md-text">
					post
				</span>
			</button>
		</div>
	</div>

	<script defer>
		window.addEventListener('load', (event) => {
			$('#add-image').click((event) => {
				$('#id_image_field').click();
				event.stopPropagation();
				event.preventDefault();
			});

			$('#id_image_field').on('change', (event) => {
				var target = $('#selected-images-field');
				target.empty();
				target.prepend(
						`<p>Selected images: ${Object.keys(event.target.files).length} <a href="#">Preview ?</a></p>`
					);
			});

			$('#add-post').on('click', (event) => {
				var postForm = $('#post-form');
				var addPostButton = $('#add-post');
				addPostButton.addClass('disabled');
				$('#post-form-alert').remove();
				$.ajax({
					'url': "{% url 'main:post-upload' %}",
					'type': 'POST',
					'data': new FormData(postForm[0]),

					contentType: false,
					processData: false,

					success: (json) => {
						if(json.status === 1){
							throwPostLoadedEvent(json.pid);
							
							$('#posts-container').prepend(json.post_html);
							postForm.trigger('reset');
							$('#selected-images-field').empty();
							postForm.prepend(`
									<div class="alert alert-success" id="post-form-alert">
										${json.message}
									</div>
								`)
							setTimeout(() => {$('#post-form-alert').remove()}, 3000);
						}else{
							var errorMsg = "";
							for(let key in json.errors)
								errorMsg += json.errors[key][0].message;
							postForm.prepend(`
									<div class="alert alert-danger" id="post-form-alert">
										${errorMsg}
									</div>
								`)
						}
						addPostButton.removeClass('disabled');
					},

					error: (xhr, errmsg, errThrow) => {
						console.error(errmsg);
						addPostButton.removeClass('disabled');
					}
				});
				event.preventDefault();
			});
		});
	</script>
{% endif %}

main/templates/main/top-users.html
<div class="rounded-bottom border border-warning bg-light p-2">
	<h5 class="text-warning">Top users</h3>
	<div class="d-flex flex-column align-items-start" id="top-users-container">
		{% if not user.is_authenticated %}
			<p class="text-warning border-bottom border-warning pb-1 w-100">log in to view</p>
		{% endif %}
	</div>
</div>

{% if user.is_authenticated %}
	<script defer>
		window.addEventListener('load', (event) => {
			function updateTopUsers(){
				$.ajax({
					'url': "{% url 'user:tops' %}",
					'type': 'GET',
					success: (json) => {
						var userItems = "";
						for(let user of json.top_users){
							userItems += `
								<div class="d-flex align-items-center w-100 pb-1 mt-2 border-bottom border-warning">
									<a href="${user.link}">
										<img class="rounded-circle border border-warning mr-2" src="${user.profile_picture_url}" width="42" height="42">
									</a>
									<div>
										<a href="${user.link}" class="md-text m-0 text-primary">${user.username}</a>
										<p class="md-text m-0">followers:&nbsp;${user.followers_count}</p>
									</div>
								</div>
							`;
						}
						$('#top-users-container').html($(userItems));
					},
					error: (xhr, errmsg, errThrow) => {
						console.error(errmsg);
					},

					complete: (xhr, status) => {
						if(status === 'success')
							setTimeout(() => {updateTopUsers();}, 60000);
					},

					'timeout': 2000
				});
			};

			updateTopUsers();
		});
	</script>
{% endif %}